#!/usr/bin/env sh
. "$(dirname "$0")/h"
if [ "$3" = "1" ]; then
  CURRENT_BRANCH=$(git branch --show-current)
  
  if [ "$CURRENT_BRANCH" = "main" ]; then
    echo "🔄 Branch main detectada! Atualizando dependências..."
    npm install
  fi
fi